# Generated by Django 6.0.5 on 2026-06-03 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=100)),
                ('cust_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('due_date', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('logged', 'Logged'), ('failed', 'Failed')], default='logged', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
