# Generated by Django 6.0.5 on 2026-06-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smslog',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='smslog',
            name='due_date',
        ),
        migrations.AddField(
            model_name='smslog',
            name='extra_fields',
            field=models.JSONField(default=dict),
        ),
    ]
