# Generated by Django 6.0.5 on 2026-05-26 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMSLog',
        ),
    ]
