# Generated by Django 6.0.5 on 2026-06-05 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_remove_smslog_amount_remove_smslog_due_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smslog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='smslog',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('logged', 'Logged'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
