# Generated by Django 6.0.5 on 2026-06-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_alter_smslog_options_smslog_scheduled_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
