# Generated by Django 6.0.5 on 2026-06-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='due_date',
        ),
        migrations.AddField(
            model_name='customer',
            name='extra_fields',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
